DJANGORESIZED_DEFAULT_SIZE = [1920, 1080]

DJANGORESIZED_DEFAULT_QUALITY = 75

DJANGORESIZED_DEFAULT_KEEP_META = True

DJANGORESIZED_DEFAULT_FORCE_FORMAT = "JPEG"

DJANGORESIZED_DEFAULT_FORMAT_EXTENSIONS = {"JPEG": ".jpg"}

DJANGORESIZED_DEFAULT_NORMALIZE_ROTATION = True
